ci(gha): remove job outputs
The gha module was generating outputs for some reason - these outputs
contained *all* of stdout and stderr, which could sometimes exceed the
total allowed object size in github actions:

    Error: The template is not valid. System.InvalidOperationException: Maximum object size exceeded

However, it didn't seem like we were ever using these outputs - we still
need to capture them for the process of producing the summary report,
but we don't actually seem to need the job outputs - so I've just gone
and removed them, which should hopefully fix the issue.

Signed-off-by: Justin Chadwell <me@jedevc.com>