Fix invalid dagger develop command (#7651)
* fix invalid dagger develop command

The command is invalid, and is missing a space.

```
❯ dagger develop...
Error: unknown command "develop..." for "dagger"
```

Signed-off-by: Eli Gladman <8713153+egladman@users.noreply.github.com>

* rm trailing ...

Signed-off-by: Eli Gladman <8713153+egladman@users.noreply.github.com>

---------

Signed-off-by: Eli Gladman <8713153+egladman@users.noreply.github.com>