chore: bump golangci lint
Something very weird was happening in the linter after the deps upgrade:

```
[typecheck] sdk/go/internal/engineconn/cli.go:43: undefined: homedir
[typecheck] sdk/go/provision_test.go:79: declared and not used: archivePath
[typecheck] sdk/go/provision_test.go:83: declared and not used: checksumPath
```

1. no deps related to these were actually updated
2. these lints are just plainly wrong, those variables *are* defined and used.

Instead of spending ages trying to understand this, it seems like just
bumping golangci lint fixes it, so doing that instead :)

Signed-off-by: Justin Chadwell <me@jedevc.com>