infra: fix action.yml version formatting
This was causing dependent pipelines, like publish, to fail with:
> Error: /home/runner/_work/dagger/dagger/./.github/actions/call/action.yml: (Line: 16, Col: 14, Idx: 290) - (Line: 16, Col: 17, Idx: 293): While parsing a quoted scalar, find unknown escape character.

Signed-off-by: Matias Pan <matias@dagger.io>