fix(ts/test): fix error TS1016: A required parameter cannot follow an optional parameter.
The test was setting an optional field in front of a mandatory one,
which triggered this error and made the test suite fail

Signed-off-by: Guillaume de Rouville <guillaume@dagger.io>